dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0

jobs:
  exclude:
    - DJANGO_VERSION: 3.0
      python: 3.5

install: 
 - pip install --upgrade pip
 - pip install Django==$DJANGO_VERSION
# Tell Travis how to run the test script itself
script: python quicktest.py shibboleth

